<div class="project">
    <h1>Vocabulary Knowledge Profiler</h1>
    <div class="description">
        <div class="container">
            <h2>The Project</h2>
            <p>
                The Vocabulary Knowledge Profiler (VKP) is an online vocabulary test for learners of English as a
                second or foreign language. It is designed to measure your written receptive vocabulary knowledge,
                that is the vocabulary knowledge that enables you to read English texts.
            </p>
            <div class="image">
                <img src="/img/projects/vkp/homepage.png">
            </div>
            <p>
                VKP tests your recognition of word meanings in a decontextualised way using four-option Multiple Choice
                items. The words tested are sampled from the most frequent 10,000 content words (lemmas) in the Corpus
                of Contemporary American English (COCA). It reports your scores according to your mastery of different
                frequency levels.
            </p>
            <div class="image">
                <img src="/img/projects/vkp/test-complete.png">
            </div>
            <p>
                The research and programming behind this site has been supported by the TOEFL Small Grant for Doctoral
                Research in Second or Foreign Language Assessment and the British Council APTIS Assessment
                Research Award.
            </p>
            <div class="image">
                <img src="/img/projects/vkp/pictures.png">
            </div>
            <p>
                There are 4 different tests that can be taken as well as the automated test which takes you through
                a randomly selected variety of questions, becoming gradually more difficult as you get questions wrong
                and re-testing areas where the results are questionable.
            </p>
            <div class="image">
                <img src="/img/projects/vkp/vocab.png">
            </div>
            <p>
                The researchers also have access to a powerful administration tool, allowing them to update and maintain
                the vocabulary database and associated images, as well as download the resultant data in several
                reporting formats generated by the system.
            </p>
            <div class="image">
                <img src="/img/projects/vkp/admin.png">
            </div>
        </div>
    </div>
    <div class="tech-stack">
        <div class="container">
            <h2>The Technology Stack</h2>
            <?php
                echo \App\App::view('components/tools', [
                    'tools' => [
                        'javascript', 'angular', 'sass', 'gulp', 'npm', 'php', 'mysql', 'laravel', 'beanstalkd', 'composer'
                    ]
                ])
            ?>
            <p>
                The application is a single-page app built with Angular, that connects to a REST API built with Laravel
                and MySQL, using Beanstalk for report generation and image manipulation queues.
            </p>
            <h2>More Information</h2>
            <p>
                Go ahead and <a href="http://vkp.alistairshaw.co.uk" target="_blank">take the test yourself!</a> It's kind of fun :)
            </p>
        </div>
    </div>
</div>
<?php echo App\App::view('projects/footer', ['exclude' => 'hygge']) ?>